version: '3.8'
services:
  reelgrab:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: reelgrab
    entrypoint: sleep infinity
    ports:
      - "5242:5242"
    volumes:
      - "./:/app:rw"
      - "./data:/data:rw"
      - "./media1:/media1:rw"
      - "./media2:/media2:rw"
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    ports:
      - "9091:9091"
  jackett:
      image: linuxserver/jackett
      container_name: jackett
      ports:
        - "9117:9117"
